// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    'intro',
    'im-nebula',
    'requirements',
    {
      type: 'category',
      label: 'Automations',
      collapsible: true,
      collapsed: true,
      items: ['Automations/intro', {type: 'autogenerated', dirName: 'Automations/usage'}],
    },
    {
      type: 'category',
      label: 'Core',
      collapsible: true,
      collapsed: true,
      items: ['Core/intro', {type: 'autogenerated', dirName: 'Core/usage'}],
    },
    {
      type: 'category',
      label: 'Log',
      collapsible: true,
      collapsed: true,
      items: ['Log/intro', {type: 'autogenerated', dirName: 'Log/usage'}],
    },
    'Scripts',
    {
      type: 'category',
      label: 'Tools',
      collapsible: true,
      collapsed: true,
      items: ['Tools/intro', {type: 'autogenerated', dirName: 'Tools/usage'}],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
